  //0
  document.getElementsByTagName('a')[0].addEventListener('click',function(){
  document.getElementsByClassName('content')[0].style.display="block";
  document.getElementsByClassName('content')[1].style.display="none";
  document.getElementsByClassName('content')[2].style.display="none";
  document.getElementsByClassName('content')[3].style.display="none";
  document.getElementsByClassName('content')[4].style.display="none";
  document.getElementsByClassName('content')[5].style.display="none";
  document.getElementsByClassName('content')[6].style.display="none";
  document.getElementsByTagName('a')[0].classList.add('active');
  document.getElementsByTagName('a')[1].classList.remove('active');
  document.getElementsByTagName('a')[2].classList.remove('active');
  document.getElementsByTagName('a')[3].classList.remove('active');
  document.getElementsByTagName('a')[4].classList.remove('active');
  document.getElementsByTagName('a')[5].classList.remove('active');
  document.getElementsByTagName('a')[6].classList.remove('active');

})
  //1
  document.getElementsByTagName('a')[1].addEventListener('click',function(){
    document.getElementsByClassName('content')[0].style.display="none";
    document.getElementsByClassName('content')[1].style.display="block";
    document.getElementsByClassName('content')[2].style.display="none";
    document.getElementsByClassName('content')[3].style.display="none";
    document.getElementsByClassName('content')[4].style.display="none";
    document.getElementsByClassName('content')[5].style.display="none";
    document.getElementsByClassName('content')[6].style.display="none";
    document.getElementsByTagName('a')[0].classList.remove('active');
    document.getElementsByTagName('a')[1].classList.add('active');
    document.getElementsByTagName('a')[2].classList.remove('active');
    document.getElementsByTagName('a')[3].classList.remove('active');
    document.getElementsByTagName('a')[4].classList.remove('active');
    document.getElementsByTagName('a')[5].classList.remove('active');
    document.getElementsByTagName('a')[6].classList.remove('active');
  
  })
    //2
    document.getElementsByTagName('a')[2].addEventListener('click',function(){
      document.getElementsByClassName('content')[0].style.display="none";
      document.getElementsByClassName('content')[1].style.display="none";
      document.getElementsByClassName('content')[2].style.display="block";
      document.getElementsByClassName('content')[3].style.display="none";
      document.getElementsByClassName('content')[4].style.display="none";
      document.getElementsByClassName('content')[5].style.display="none";
      document.getElementsByClassName('content')[6].style.display="none";
      document.getElementsByTagName('a')[0].classList.remove('active');
      document.getElementsByTagName('a')[1].classList.remove('active');
      document.getElementsByTagName('a')[2].classList.add('active');
      document.getElementsByTagName('a')[3].classList.remove('active');
      document.getElementsByTagName('a')[4].classList.remove('active');
      document.getElementsByTagName('a')[5].classList.remove('active');
      document.getElementsByTagName('a')[6].classList.remove('active');
    
    })
      //3
      document.getElementsByTagName('a')[3].addEventListener('click',function(){
        document.getElementsByClassName('content')[0].style.display="none";
        document.getElementsByClassName('content')[1].style.display="none";
        document.getElementsByClassName('content')[2].style.display="none";
        document.getElementsByClassName('content')[3].style.display="block";
        document.getElementsByClassName('content')[4].style.display="none";
        document.getElementsByClassName('content')[5].style.display="none";
        document.getElementsByClassName('content')[6].style.display="none";
        document.getElementsByTagName('a')[0].classList.remove('active');
        document.getElementsByTagName('a')[1].classList.remove('active');
        document.getElementsByTagName('a')[2].classList.remove('active');
        document.getElementsByTagName('a')[3].classList.add('active');
        document.getElementsByTagName('a')[4].classList.remove('active');
        document.getElementsByTagName('a')[5].classList.remove('active');
        document.getElementsByTagName('a')[6].classList.remove('active');
      
      })
      //4
      document.getElementsByTagName('a')[4].addEventListener('click',function(){
        document.getElementsByClassName('content')[0].style.display="none";
        document.getElementsByClassName('content')[1].style.display="none";
        document.getElementsByClassName('content')[2].style.display="none";
        document.getElementsByClassName('content')[3].style.display="none";
        document.getElementsByClassName('content')[4].style.display="block";
        document.getElementsByClassName('content')[5].style.display="none";
        document.getElementsByClassName('content')[6].style.display="none";
        document.getElementsByTagName('a')[0].classList.remove('active');
        document.getElementsByTagName('a')[1].classList.remove('active');
        document.getElementsByTagName('a')[2].classList.remove('active');
        document.getElementsByTagName('a')[3].classList.remove('active');
        document.getElementsByTagName('a')[4].classList.add('active');
        document.getElementsByTagName('a')[5].classList.remove('active');
        document.getElementsByTagName('a')[6].classList.remove('active');
      
      })
      //5
      document.getElementsByTagName('a')[5].addEventListener('click',function(){
        document.getElementsByClassName('content')[0].style.display="none";
        document.getElementsByClassName('content')[1].style.display="none";
        document.getElementsByClassName('content')[2].style.display="none";
        document.getElementsByClassName('content')[3].style.display="none";
        document.getElementsByClassName('content')[4].style.display="none";
        document.getElementsByClassName('content')[5].style.display="block";
        document.getElementsByClassName('content')[6].style.display="none";
        document.getElementsByTagName('a')[0].classList.remove('active');
        document.getElementsByTagName('a')[1].classList.remove('active');
        document.getElementsByTagName('a')[2].classList.remove('active');
        document.getElementsByTagName('a')[3].classList.remove('active');
        document.getElementsByTagName('a')[4].classList.remove('active');
        document.getElementsByTagName('a')[5].classList.add('active');
        document.getElementsByTagName('a')[6].classList.remove('active');
      
      })
      //6
      document.getElementsByTagName('a')[6].addEventListener('click',function(){
        document.getElementsByClassName('content')[0].style.display="none";
        document.getElementsByClassName('content')[1].style.display="none";
        document.getElementsByClassName('content')[2].style.display="none";
        document.getElementsByClassName('content')[3].style.display="none";
        document.getElementsByClassName('content')[4].style.display="none";
        document.getElementsByClassName('content')[5].style.display="none";
        document.getElementsByClassName('content')[6].style.display="block";
        document.getElementsByTagName('a')[0].classList.remove('active');
        document.getElementsByTagName('a')[1].classList.remove('active');
        document.getElementsByTagName('a')[2].classList.remove('active');
        document.getElementsByTagName('a')[3].classList.remove('active');
        document.getElementsByTagName('a')[4].classList.remove('active');
        document.getElementsByTagName('a')[5].classList.remove('active');
        document.getElementsByTagName('a')[6].classList.add('active');
      
      })
